name = "notification-service"
main = "index.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sec_filings"
database_id = "becbe21b-9435-4df7-80da-3df9ed7f1b96"

# Schedule: Run every 5 minutes to process notification queue
[triggers]
crons = ["*/5 * * * *"]

# Observability
[observability.logs]
enabled = true

# Environment variables (non-sensitive)
[vars]
FROM_EMAIL = "alerts@yourdomain.com"
FROM_NAME = "SEC Insider Alerts"
MAX_BATCH_SIZE = "50"

# Secrets (set these with: wrangler secret put SECRET_NAME)
# MAILGUN_API_KEY
# MAILGUN_DOMAIN
