name = "rss-monitor"
main = "index.js"
compatibility_date = "2023-12-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sec_filings"
database_id = "becbe21b-9435-4df7-80da-3df9ed7f1b96"

# Queue for processing tasks (producer only)
[[queues.producers]]
binding = "filing_processing_queue"
queue = "filing-processing-queue"

# Cron triggers for RSS monitoring
[triggers]
crons = ["* * * * *"]  # Run every minute (fastest possible)

[observability.logs]
enabled = true

# Environment variables
[vars]
SEC_RSS_URL = "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&CIK=&type=&company=&dateb=&owner=include&start=0&count=40&output=atom"
