name = 'sec-frontend'
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[vars]
NEXT_PUBLIC_API_URL = "https://api-server.benjamin-sautersb.workers.dev"
NEXT_PUBLIC_AUTH_URL = "https://auth-worker.benjamin-sautersb.workers.dev"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

