name = "api-server"
main = "index.js"
compatibility_date = "2025-03-25"

# Environment variables
[env.production.vars]
CORS_ORIGINS = "https://your-frontend-domain.com"

[env.development.vars]
CORS_ORIGINS = "http://localhost:3000"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "sec_filings"
database_id = "becbe21b-9435-4df7-80da-3df9ed7f1b96"

# Service binding to historical-importer worker
[[services]]
binding = "HISTORICAL_IMPORTER"
service = "historical-importer"

